version: "3"
networks:
  nocobase:
    driver: bridge

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        VERDACCIO_URL: "http://verdaccio:4873"  # 构建阶段不访问它，安全保留
    networks:
      - nocobase
    environment:
      - APP_KEY=your-secret-key
      - ENCRYPTION_FIELD_KEY=your-secret-key
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=nocobase
      - VERDACCIO_URL=http://registry.npmjs.org
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
    depends_on:
      - postgres
      - verdaccio
    init: true
    command: >
      sh -c "
      echo '✔ App started';
      echo '⏳ Waiting for verdaccio...';
      sleep 5;
      echo '🚀 Running yarn release:force';
      yarn release:force --registry $VERDACCIO_URL || echo '⚠️ yarn release 失败，跳过...';
      yarn start
      "

  postgres:
    image: postgres:10
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: nocobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase

  verdaccio:
    image: verdaccio/verdaccio
    networks:
      - nocobase
    ports:
      - "4873:4873"
