version: "3"
networks:
  nocobase:
    driver: bridge

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        VERDACCIO_URL: "http://172.17.0.1:10104"  # ✅ 构建参数传入 Dockerfile
    networks:
      - nocobase
    environment:
      - APP_KEY=your-secret-key # Replace it with your own app key
      - ENCRYPTION_FIELD_KEY=your-secret-key # Replace it with your own app key
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=nocobase
      - VERDACCIO_URL=http://172.17.0.1:10104    # ✅ 可选：运行时环境变量
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
    depends_on:
      - postgres
    init: true

  postgres:
    image: postgres:10
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: nocobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase
