version: "3"
networks:
  nocobase:
    driver: bridge

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        VERDACCIO_URL: "https://registry.npmjs.org"
    networks:
      - nocobase
    environment:
      - APP_KEY=your-secret-key
      - ENCRYPTION_FIELD_KEY=your-secret-key
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=nocobase
      - VERDACCIO_URL=https://registry.npmjs.org
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
    depends_on:
      - postgres
    init: true
    command: >
      sh -c "
      echo '✔ App started';
      yarn release:force --registry $VERDACCIO_URL || echo '⚠️ yarn release 失败，跳过...';
      yarn start
      "

  postgres:
    image: postgres:10
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: nocobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase

